// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: components.sql

package dbsqlc

import (
	"context"
)

const createComponent = `-- name: CreateComponent :execlastid
INSERT INTO components (name, description) VALUES (?, ?)
`

type CreateComponentParams struct {
	Name        string
	Description string
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createComponent, arg.Name, arg.Description)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getComponentByName = `-- name: GetComponentByName :one
SELECT id, name, description, created_at FROM components WHERE name = ?
`

func (q *Queries) GetComponentByName(ctx context.Context, name string) (Component, error) {
	row := q.db.QueryRowContext(ctx, getComponentByName, name)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listComponents = `-- name: ListComponents :many
SELECT id, name, description, created_at FROM components ORDER BY name
`

func (q *Queries) ListComponents(ctx context.Context) ([]Component, error) {
	rows, err := q.db.QueryContext(ctx, listComponents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Component
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
