// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fbc.sql

package dbsqlc

import (
	"context"
)

const deleteFBCCatalogBundles = `-- name: DeleteFBCCatalogBundles :exec
DELETE FROM fbc_catalog_bundles WHERE catalog_digest = ?
`

func (q *Queries) DeleteFBCCatalogBundles(ctx context.Context, catalogDigest string) error {
	_, err := q.db.ExecContext(ctx, deleteFBCCatalogBundles, catalogDigest)
	return err
}

const getFBCCatalogState = `-- name: GetFBCCatalogState :one
SELECT state FROM fbc_catalogs WHERE digest = ?
`

func (q *Queries) GetFBCCatalogState(ctx context.Context, digest string) (string, error) {
	row := q.db.QueryRowContext(ctx, getFBCCatalogState, digest)
	var state string
	err := row.Scan(&state)
	return state, err
}

const getLatestSnapshotImage = `-- name: GetLatestSnapshotImage :one
SELECT s.name, sc.image_url
FROM snapshots s
JOIN snapshot_components sc ON sc.snapshot_id = s.id
WHERE s.application = ? AND sc.component = ?
  AND NOT EXISTS (SELECT 1 FROM staged_snapshots ss WHERE ss.name = s.name)
ORDER BY s.created_at DESC, s.id DESC
LIMIT 1
`

type GetLatestSnapshotImageParams struct {
	Application string
	Component   string
}

type GetLatestSnapshotImageRow struct {
	Name     string
	ImageUrl string
}

// The newest Snapshot of an application holding a component, with its image,
// skipping the Snapshots ART staged.
func (q *Queries) GetLatestSnapshotImage(ctx context.Context, arg GetLatestSnapshotImageParams) (GetLatestSnapshotImageRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestSnapshotImage, arg.Application, arg.Component)
	var i GetLatestSnapshotImageRow
	err := row.Scan(&i.Name, &i.ImageUrl)
	return i, err
}

const insertFBCCatalogBundle = `-- name: InsertFBCCatalogBundle :exec
INSERT INTO fbc_catalog_bundles (catalog_digest, package, channel, bundle_name, bundle_ref, bundle_digest)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertFBCCatalogBundleParams struct {
	CatalogDigest string
	Package       string
	Channel       string
	BundleName    string
	BundleRef     string
	BundleDigest  string
}

func (q *Queries) InsertFBCCatalogBundle(ctx context.Context, arg InsertFBCCatalogBundleParams) error {
	_, err := q.db.ExecContext(ctx, insertFBCCatalogBundle,
		arg.CatalogDigest,
		arg.Package,
		arg.Channel,
		arg.BundleName,
		arg.BundleRef,
		arg.BundleDigest,
	)
	return err
}

const listFBCCatalogBundles = `-- name: ListFBCCatalogBundles :many
SELECT package, channel, bundle_name, bundle_ref, bundle_digest
FROM fbc_catalog_bundles
WHERE catalog_digest = ? AND package = ? AND channel = ?
ORDER BY bundle_name
`

type ListFBCCatalogBundlesParams struct {
	CatalogDigest string
	Package       string
	Channel       string
}

type ListFBCCatalogBundlesRow struct {
	Package      string
	Channel      string
	BundleName   string
	BundleRef    string
	BundleDigest string
}

func (q *Queries) ListFBCCatalogBundles(ctx context.Context, arg ListFBCCatalogBundlesParams) ([]ListFBCCatalogBundlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFBCCatalogBundles, arg.CatalogDigest, arg.Package, arg.Channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFBCCatalogBundlesRow
	for rows.Next() {
		var i ListFBCCatalogBundlesRow
		if err := rows.Scan(
			&i.Package,
			&i.Channel,
			&i.BundleName,
			&i.BundleRef,
			&i.BundleDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFBCCatalogCandidates = `-- name: ListFBCCatalogCandidates :many
SELECT sc.image_url
FROM snapshot_components sc
JOIN snapshots s ON s.id = sc.snapshot_id
LEFT JOIN fbc_catalogs c ON c.digest = substr(sc.image_url, instr(sc.image_url, '@') + 1)
WHERE s.application LIKE 'fbc-%'
  AND sc.component = s.application || '-quay-operator'
  AND instr(sc.image_url, '@sha256:') > 0
  AND s.id = (SELECT s2.id
              FROM snapshots s2
              JOIN snapshot_components sc2 ON sc2.snapshot_id = s2.id
              WHERE s2.application = s.application AND sc2.component = sc.component
                AND NOT EXISTS (SELECT 1 FROM staged_snapshots ss WHERE ss.name = s2.name)
              ORDER BY s2.created_at DESC, s2.id DESC
              LIMIT 1)
  AND (c.digest IS NULL OR (c.state = 'failed' AND c.checked_at < ?))
ORDER BY s.created_at DESC
LIMIT ?
`

type ListFBCCatalogCandidatesParams struct {
	CheckedAt string
	Limit     int64
}

// The quay-operator image of each FBC application's newest Snapshot holding
// one, when its catalog is unread or its last read failed before the cutoff.
// Snapshots ART staged share the application and component but are not the
// stream's builds, so they are skipped.
func (q *Queries) ListFBCCatalogCandidates(ctx context.Context, arg ListFBCCatalogCandidatesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listFBCCatalogCandidates, arg.CheckedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var image_url string
		if err := rows.Scan(&image_url); err != nil {
			return nil, err
		}
		items = append(items, image_url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFBCCatalog = `-- name: UpsertFBCCatalog :exec
INSERT INTO fbc_catalogs (digest, state, checked_at)
VALUES (?, ?, ?)
ON CONFLICT(digest) DO UPDATE SET
    state = excluded.state,
    checked_at = excluded.checked_at
`

type UpsertFBCCatalogParams struct {
	Digest    string
	State     string
	CheckedAt string
}

func (q *Queries) UpsertFBCCatalog(ctx context.Context, arg UpsertFBCCatalogParams) error {
	_, err := q.db.ExecContext(ctx, upsertFBCCatalog, arg.Digest, arg.State, arg.CheckedAt)
	return err
}
