// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: konflux_releases.sql

package dbsqlc

import (
	"context"
	"strings"
)

const listKonfluxReleasesBySnapshots = `-- name: ListKonfluxReleasesBySnapshots :many
SELECT id, name, application, snapshot, release_plan, released_status, released_reason, failed_task, failed_step, created_at, start_time, completion_time
FROM konflux_releases
WHERE snapshot IN (/*SLICE:snapshots*/?)
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListKonfluxReleasesBySnapshots(ctx context.Context, snapshots []string) ([]KonfluxRelease, error) {
	query := listKonfluxReleasesBySnapshots
	var queryParams []interface{}
	if len(snapshots) > 0 {
		for _, v := range snapshots {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:snapshots*/?", strings.Repeat(",?", len(snapshots))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:snapshots*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KonfluxRelease
	for rows.Next() {
		var i KonfluxRelease
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Application,
			&i.Snapshot,
			&i.ReleasePlan,
			&i.ReleasedStatus,
			&i.ReleasedReason,
			&i.FailedTask,
			&i.FailedStep,
			&i.CreatedAt,
			&i.StartTime,
			&i.CompletionTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertKonfluxRelease = `-- name: UpsertKonfluxRelease :exec
INSERT INTO konflux_releases (name, application, snapshot, release_plan, released_status, released_reason, failed_task, failed_step, created_at, start_time, completion_time)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    application=excluded.application,
    snapshot=excluded.snapshot,
    release_plan=excluded.release_plan,
    released_status=excluded.released_status,
    released_reason=excluded.released_reason,
    failed_task=excluded.failed_task,
    failed_step=excluded.failed_step,
    created_at=excluded.created_at,
    start_time=excluded.start_time,
    completion_time=excluded.completion_time
`

type UpsertKonfluxReleaseParams struct {
	Name           string
	Application    string
	Snapshot       string
	ReleasePlan    string
	ReleasedStatus string
	ReleasedReason string
	FailedTask     string
	FailedStep     string
	CreatedAt      string
	StartTime      string
	CompletionTime string
}

func (q *Queries) UpsertKonfluxRelease(ctx context.Context, arg UpsertKonfluxReleaseParams) error {
	_, err := q.db.ExecContext(ctx, upsertKonfluxRelease,
		arg.Name,
		arg.Application,
		arg.Snapshot,
		arg.ReleasePlan,
		arg.ReleasedStatus,
		arg.ReleasedReason,
		arg.FailedTask,
		arg.FailedStep,
		arg.CreatedAt,
		arg.StartTime,
		arg.CompletionTime,
	)
	return err
}
