// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

type Component struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   string
}

type JiraIssue struct {
	ID         int64
	Key        string
	Summary    string
	Status     string
	Priority   string
	Labels     string
	FixVersion string
	Assignee   string
	IssueType  string
	Resolution string
	Link       string
	UpdatedAt  string
}

type ReleaseVersion struct {
	ID                    int64
	Name                  string
	Description           string
	ReleaseDate           string
	Released              int64
	Archived              int64
	ReleaseTicketKey      string
	ReleaseTicketAssignee string
	S3Application         string
	DueDate               string
}

type Snapshot struct {
	ID          int64
	Application string
	Name        string
	TestsPassed int64
	CreatedAt   string
}

type SnapshotComponent struct {
	ID         int64
	SnapshotID int64
	Component  string
	GitSha     string
	ImageUrl   string
	GitUrl     string
}

type TestCase struct {
	ID          int64
	TestSuiteID int64
	Name        string
	Status      string
	DurationMs  float64
	Message     string
	Trace       string
	FilePath    string
	Suite       string
	Retries     int64
	Flaky       int64
}

type TestSuite struct {
	ID          int64
	SnapshotID  int64
	Name        string
	Status      string
	PipelineRun string
	ToolName    string
	ToolVersion string
	Tests       int64
	Passed      int64
	Failed      int64
	Skipped     int64
	Pending     int64
	Other       int64
	Flaky       int64
	StartTime   int64
	StopTime    int64
	DurationMs  int64
	CreatedAt   string
}
