// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

type ArtBuild struct {
	Digest       string
	State        string
	Nvr          string
	RecordID     string
	UpstreamRepo string
	UpstreamSha  string
	CheckedAt    string
}

type ArtBuildAttempt struct {
	GroupName      string
	RecordID       string
	ReleaseVersion string
	Component      string
	Nvr            string
	Outcome        string
	StartTime      string
	FirstSeen      string
	LastSeen       string
}

type ArtBuildCoverage struct {
	GroupName   string
	CoveredFrom string
	CoveredTo   string
}

type ArtPendingBuild struct {
	GroupName      string
	ReleaseVersion string
	Component      string
	Nvr            string
	RecordID       string
	UpstreamSha    string
	StartedAt      string
	CheckedAt      string
}

type FbcCatalog struct {
	Digest    string
	State     string
	CheckedAt string
}

type FbcCatalogBundle struct {
	CatalogDigest string
	Package       string
	Channel       string
	BundleName    string
	BundleRef     string
	BundleDigest  string
}

type JiraIssue struct {
	ID         int64
	Key        string
	Summary    string
	Status     string
	Priority   string
	Labels     string
	FixVersion string
	Assignee   string
	IssueType  string
	Link       string
	QaContact  string
}

type KonfluxRelease struct {
	ID             int64
	Name           string
	Application    string
	Snapshot       string
	ReleasePlan    string
	ReleasedStatus string
	ReleasedReason string
	FailedTask     string
	FailedStep     string
	CreatedAt      string
	StartTime      string
	CompletionTime string
}

type ProwRun struct {
	JobName       string
	BuildID       string
	Kind          string
	Application   string
	State         string
	StartedAt     string
	CompletedAt   string
	ProwUrl       string
	ArtifactState string
	CatalogRef    string
	FetchedAt     string
}

type ProwRunImage struct {
	ID      int64
	JobName string
	BuildID string
	Role    string
	Digest  string
}

type ProwSync struct {
	JobName            string
	Application        string
	IntervalSeconds    int64
	LastSuccessfulSync string
}

type ReleaseVersion struct {
	ID                    int64
	Name                  string
	ReleaseDate           string
	Released              int64
	Archived              int64
	ReleaseTicketKey      string
	ReleaseTicketAssignee string
	KonfluxApplication    string
	DueDate               string
}

type Snapshot struct {
	ID          int64
	Application string
	Name        string
	CreatedAt   string
}

type SnapshotComponent struct {
	ID         int64
	SnapshotID int64
	Component  string
	ImageUrl   string
}

type StagedSnapshot struct {
	Name      string
	Assembly  string
	Kind      string
	Env       string
	CreatedAt string
}
