// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prow.sql

package dbsqlc

import (
	"context"
)

const deleteProwRunImages = `-- name: DeleteProwRunImages :exec
DELETE FROM prow_run_images WHERE job_name = ? AND build_id = ?
`

type DeleteProwRunImagesParams struct {
	JobName string
	BuildID string
}

func (q *Queries) DeleteProwRunImages(ctx context.Context, arg DeleteProwRunImagesParams) error {
	_, err := q.db.ExecContext(ctx, deleteProwRunImages, arg.JobName, arg.BuildID)
	return err
}

const insertProwRunImage = `-- name: InsertProwRunImage :exec
INSERT INTO prow_run_images (job_name, build_id, role, digest)
VALUES (?, ?, ?, ?)
`

type InsertProwRunImageParams struct {
	JobName string
	BuildID string
	Role    string
	Digest  string
}

func (q *Queries) InsertProwRunImage(ctx context.Context, arg InsertProwRunImageParams) error {
	_, err := q.db.ExecContext(ctx, insertProwRunImage,
		arg.JobName,
		arg.BuildID,
		arg.Role,
		arg.Digest,
	)
	return err
}

const listFinishedProwBuildIDs = `-- name: ListFinishedProwBuildIDs :many
SELECT build_id FROM prow_runs WHERE job_name = ? AND completed_at != ''
`

func (q *Queries) ListFinishedProwBuildIDs(ctx context.Context, jobName string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listFinishedProwBuildIDs, jobName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var build_id string
		if err := rows.Scan(&build_id); err != nil {
			return nil, err
		}
		items = append(items, build_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProwRunImages = `-- name: ListProwRunImages :many
SELECT role, digest
FROM prow_run_images
WHERE job_name = ? AND build_id = ?
ORDER BY id
`

type ListProwRunImagesParams struct {
	JobName string
	BuildID string
}

type ListProwRunImagesRow struct {
	Role   string
	Digest string
}

func (q *Queries) ListProwRunImages(ctx context.Context, arg ListProwRunImagesParams) ([]ListProwRunImagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProwRunImages, arg.JobName, arg.BuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProwRunImagesRow
	for rows.Next() {
		var i ListProwRunImagesRow
		if err := rows.Scan(&i.Role, &i.Digest); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProwRunsByApplication = `-- name: ListProwRunsByApplication :many
SELECT job_name, build_id, kind, application, state, started_at, completed_at, prow_url, artifact_state, catalog_ref, fetched_at
FROM prow_runs
WHERE application = ?
ORDER BY started_at DESC, build_id DESC
`

func (q *Queries) ListProwRunsByApplication(ctx context.Context, application string) ([]ProwRun, error) {
	rows, err := q.db.QueryContext(ctx, listProwRunsByApplication, application)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProwRun
	for rows.Next() {
		var i ProwRun
		if err := rows.Scan(
			&i.JobName,
			&i.BuildID,
			&i.Kind,
			&i.Application,
			&i.State,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ProwUrl,
			&i.ArtifactState,
			&i.CatalogRef,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProwSyncs = `-- name: ListProwSyncs :many
SELECT job_name, application, interval_seconds, last_successful_sync FROM prow_syncs
`

func (q *Queries) ListProwSyncs(ctx context.Context) ([]ProwSync, error) {
	rows, err := q.db.QueryContext(ctx, listProwSyncs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProwSync
	for rows.Next() {
		var i ProwSync
		if err := rows.Scan(
			&i.JobName,
			&i.Application,
			&i.IntervalSeconds,
			&i.LastSuccessfulSync,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProwRun = `-- name: UpsertProwRun :exec
INSERT INTO prow_runs (job_name, build_id, kind, application, state, started_at, completed_at, prow_url, artifact_state, catalog_ref, fetched_at)
VALUES (?, ?, 'periodic', ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(job_name, build_id) DO UPDATE SET
    application=excluded.application,
    state=excluded.state,
    started_at=excluded.started_at,
    completed_at=excluded.completed_at,
    prow_url=excluded.prow_url,
    artifact_state=excluded.artifact_state,
    catalog_ref=excluded.catalog_ref,
    fetched_at=excluded.fetched_at
`

type UpsertProwRunParams struct {
	JobName       string
	BuildID       string
	Application   string
	State         string
	StartedAt     string
	CompletedAt   string
	ProwUrl       string
	ArtifactState string
	CatalogRef    string
	FetchedAt     string
}

func (q *Queries) UpsertProwRun(ctx context.Context, arg UpsertProwRunParams) error {
	_, err := q.db.ExecContext(ctx, upsertProwRun,
		arg.JobName,
		arg.BuildID,
		arg.Application,
		arg.State,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ProwUrl,
		arg.ArtifactState,
		arg.CatalogRef,
		arg.FetchedAt,
	)
	return err
}

const upsertProwSync = `-- name: UpsertProwSync :exec
INSERT INTO prow_syncs (job_name, application, interval_seconds, last_successful_sync)
VALUES (?, ?, ?, ?)
ON CONFLICT(job_name) DO UPDATE SET
    application=excluded.application,
    interval_seconds=excluded.interval_seconds,
    last_successful_sync=excluded.last_successful_sync
`

type UpsertProwSyncParams struct {
	JobName            string
	Application        string
	IntervalSeconds    int64
	LastSuccessfulSync string
}

func (q *Queries) UpsertProwSync(ctx context.Context, arg UpsertProwSyncParams) error {
	_, err := q.db.ExecContext(ctx, upsertProwSync,
		arg.JobName,
		arg.Application,
		arg.IntervalSeconds,
		arg.LastSuccessfulSync,
	)
	return err
}
