// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package dbsqlc

import (
	"context"
)

const createSnapshot = `-- name: CreateSnapshot :execlastid
INSERT INTO snapshots (application, name, created_at)
VALUES (?, ?, ?)
`

type CreateSnapshotParams struct {
	Application string
	Name        string
	CreatedAt   string
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSnapshot, arg.Application, arg.Name, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createSnapshotComponent = `-- name: CreateSnapshotComponent :exec
INSERT INTO snapshot_components (snapshot_id, component, image_url)
VALUES (?, ?, ?)
`

type CreateSnapshotComponentParams struct {
	SnapshotID int64
	Component  string
	ImageUrl   string
}

func (q *Queries) CreateSnapshotComponent(ctx context.Context, arg CreateSnapshotComponentParams) error {
	_, err := q.db.ExecContext(ctx, createSnapshotComponent, arg.SnapshotID, arg.Component, arg.ImageUrl)
	return err
}

const getSnapshotRow = `-- name: GetSnapshotRow :one
SELECT id, application, name, created_at
FROM snapshots WHERE name = ?
`

func (q *Queries) GetSnapshotRow(ctx context.Context, name string) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotRow, name)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.Application,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listSnapshotComponents = `-- name: ListSnapshotComponents :many
SELECT id, snapshot_id, component, image_url
FROM snapshot_components
WHERE snapshot_id = ?
ORDER BY component
`

func (q *Queries) ListSnapshotComponents(ctx context.Context, snapshotID int64) ([]SnapshotComponent, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotComponents, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotComponent
	for rows.Next() {
		var i SnapshotComponent
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Component,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamBuildImages = `-- name: ListStreamBuildImages :many
SELECT s.name, s.created_at, sc.component, sc.image_url, CAST(COALESCE(a.nvr, '') AS TEXT) AS nvr
FROM snapshots s
JOIN snapshot_components sc ON sc.snapshot_id = s.id
LEFT JOIN art_builds a ON a.state = 'resolved'
  AND a.digest = substr(sc.image_url, instr(sc.image_url, '@') + 1)
WHERE s.application = ? AND s.name NOT LIKE 'fbc-ri-%'
  AND NOT EXISTS (SELECT 1 FROM staged_snapshots ss WHERE ss.name = s.name)
ORDER BY s.created_at DESC, s.name DESC, sc.component
`

type ListStreamBuildImagesRow struct {
	Name      string
	CreatedAt string
	Component string
	ImageUrl  string
	Nvr       string
}

// The component images of the application's stream builds, newest first, each
// with the NVR of its digest's resolved ART build, or ”. ART's assembly
// Snapshots (staged_snapshots) and its fbc-ri-* re-releases of a bundle's
// related images are not stream builds.
func (q *Queries) ListStreamBuildImages(ctx context.Context, application string) ([]ListStreamBuildImagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listStreamBuildImages, application)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStreamBuildImagesRow
	for rows.Next() {
		var i ListStreamBuildImagesRow
		if err := rows.Scan(
			&i.Name,
			&i.CreatedAt,
			&i.Component,
			&i.ImageUrl,
			&i.Nvr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotExistsByName = `-- name: SnapshotExistsByName :one
SELECT COUNT(*) FROM snapshots WHERE name = ?
`

func (q *Queries) SnapshotExistsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, snapshotExistsByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}
