// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staged.sql

package dbsqlc

import (
	"context"
)

const latestStagedSnapshot = `-- name: LatestStagedSnapshot :one
SELECT name, assembly, kind, env, created_at
FROM staged_snapshots ss
WHERE assembly = ?1 AND kind = ?2 AND env = 'stage'
  AND (CAST(?3 AS TEXT) = '' OR EXISTS (
      SELECT 1
      FROM snapshots s
      JOIN snapshot_components sc ON sc.snapshot_id = s.id
      WHERE s.name = ss.name AND sc.component = ?3))
ORDER BY created_at DESC, name DESC
LIMIT 1
`

type LatestStagedSnapshotParams struct {
	Assembly  string
	Kind      string
	Component string
}

// An empty component matches any Snapshot.
func (q *Queries) LatestStagedSnapshot(ctx context.Context, arg LatestStagedSnapshotParams) (StagedSnapshot, error) {
	row := q.db.QueryRowContext(ctx, latestStagedSnapshot, arg.Assembly, arg.Kind, arg.Component)
	var i StagedSnapshot
	err := row.Scan(
		&i.Name,
		&i.Assembly,
		&i.Kind,
		&i.Env,
		&i.CreatedAt,
	)
	return i, err
}

const listSuccessfulStageReleases = `-- name: ListSuccessfulStageReleases :many
SELECT kr.release_plan, kr.completion_time, s.id AS snapshot_id, s.name AS snapshot_name
FROM staged_snapshots ss
JOIN snapshots s ON s.name = ss.name
JOIN konflux_releases kr ON kr.snapshot = s.name AND kr.application = s.application
WHERE ss.assembly = ?1 AND ss.kind = 'image' AND ss.env = 'stage'
  AND s.application = ?2
  AND kr.released_status = 'True' AND kr.released_reason = 'Succeeded' AND kr.completion_time != ''
ORDER BY kr.completion_time DESC, kr.created_at DESC, kr.name DESC
`

type ListSuccessfulStageReleasesParams struct {
	Assembly    string
	Application string
}

type ListSuccessfulStageReleasesRow struct {
	ReleasePlan    string
	CompletionTime string
	SnapshotID     int64
	SnapshotName   string
}

func (q *Queries) ListSuccessfulStageReleases(ctx context.Context, arg ListSuccessfulStageReleasesParams) ([]ListSuccessfulStageReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSuccessfulStageReleases, arg.Assembly, arg.Application)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuccessfulStageReleasesRow
	for rows.Next() {
		var i ListSuccessfulStageReleasesRow
		if err := rows.Scan(
			&i.ReleasePlan,
			&i.CompletionTime,
			&i.SnapshotID,
			&i.SnapshotName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const streamStaged = `-- name: StreamStaged :one
SELECT CAST(EXISTS (
    SELECT 1 FROM staged_snapshots
    WHERE env = 'stage' AND assembly LIKE CAST(?1 AS TEXT) || '.%'
) AS BOOLEAN) AS staged
`

// The '.' after stream X.Y keeps 3.1 from matching assembly 3.18.1.
func (q *Queries) StreamStaged(ctx context.Context, stream string) (bool, error) {
	row := q.db.QueryRowContext(ctx, streamStaged, stream)
	var staged bool
	err := row.Scan(&staged)
	return staged, err
}

const upsertStagedSnapshot = `-- name: UpsertStagedSnapshot :exec
INSERT INTO staged_snapshots (name, assembly, kind, env, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    assembly=excluded.assembly,
    kind=excluded.kind,
    env=excluded.env,
    created_at=excluded.created_at
`

type UpsertStagedSnapshotParams struct {
	Name      string
	Assembly  string
	Kind      string
	Env       string
	CreatedAt string
}

func (q *Queries) UpsertStagedSnapshot(ctx context.Context, arg UpsertStagedSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertStagedSnapshot,
		arg.Name,
		arg.Assembly,
		arg.Kind,
		arg.Env,
		arg.CreatedAt,
	)
	return err
}
