apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: release-readiness-its
spec:
  params:
    - name: SNAPSHOT
      type: string
      description: Konflux Snapshot JSON
    - name: VERSION
      type: string
      description: Release version (e.g. 3.16.2)
    - name: DASHBOARD_URL
      type: string
      description: Build dashboard server URL
  tasks:
    - name: register-builds
      taskSpec:
        params:
          - name: SNAPSHOT
            type: string
          - name: VERSION
            type: string
          - name: DASHBOARD_URL
            type: string
        steps:
          - name: parse-and-register
            image: quay.io/quay/release-readiness:latest
            script: |
              #!/bin/sh
              set -e
              echo '$(params.SNAPSHOT)' > /tmp/snapshot.json

              # Convert Snapshot JSON to YAML-like format for the CLI
              # The CLI expects YAML, so we write the snapshot as-is and use it
              dashboard report snapshot \
                -server "$(params.DASHBOARD_URL)" \
                -version "$(params.VERSION)" \
                /tmp/snapshot.json
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: VERSION
          value: $(params.VERSION)
        - name: DASHBOARD_URL
          value: $(params.DASHBOARD_URL)

    - name: run-tests
      runAfter:
        - register-builds
      taskSpec:
        params:
          - name: SNAPSHOT
            type: string
        results:
          - name: TEST_OUTPUT
            description: Test output in HACBS format
        steps:
          - name: run-tests
            image: quay.io/quay/quay-tests:latest
            script: |
              #!/bin/sh
              set -e
              echo "Running integration tests..."
              # Test execution is environment-specific
              # JUnit XML results should be written to /tmp/results/
              mkdir -p /tmp/results

              # Placeholder: actual test execution goes here
              # The test framework writes JUnit XML to /tmp/results/

              TEST_OUTPUT=$(cat <<'ENDMSG'
              {"result":"SUCCESS","successes":0,"failures":0,"warnings":0}
              ENDMSG
              )
              echo "${TEST_OUTPUT}" | tee $(results.TEST_OUTPUT.path)
        workspaces:
          - name: results
            description: Test result artifacts
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      workspaces:
        - name: results
          workspace: results

    - name: report-results
      runAfter:
        - run-tests
      taskSpec:
        params:
          - name: DASHBOARD_URL
            type: string
          - name: VERSION
            type: string
        steps:
          - name: report
            image: quay.io/quay/release-readiness:latest
            script: |
              #!/bin/sh
              set -e
              RESULTS_DIR=/workspace/results

              # Report results for each test suite found
              for xml in "${RESULTS_DIR}"/*.xml; do
                [ -f "$xml" ] || continue
                echo "Reporting results from: $xml"

                # Extract suite name from filename
                SUITE=$(basename "$xml" .xml | sed 's/_/-/g')

                # Find the build ID for the component
                # In practice, build IDs are passed from register-builds
                dashboard report results \
                  -server "$(params.DASHBOARD_URL)" \
                  -build-id 1 \
                  -suite "$SUITE" \
                  "$xml"
              done
        workspaces:
          - name: results
            description: Test result artifacts
      params:
        - name: DASHBOARD_URL
          value: $(params.DASHBOARD_URL)
        - name: VERSION
          value: $(params.VERSION)
      workspaces:
        - name: results
          workspace: results

  workspaces:
    - name: results
      description: Shared workspace for test results
